project_name: circonus-agent

before:
    hooks:
        - go mod tidy
        - ./build_lint.sh
        - ./build_plugins.sh

builds:
    -
        main: main.go

        binary: sbin/circonus-agentd

        env:
            - CGO_ENABLED=0

        flags: -tags dev

        goos:
            - linux
            - darwin
            - windows
            - freebsd
            - solaris
            - illumos

        goarch:
            - amd64
            - arm64
            - arm

        ignore:
            -
                goarch: 386
            - goos: freebsd
              goarch: arm

        ldflags: 
            - -X github.com/circonus-labs/circonus-agent/internal/release.VERSION={{.Version}} 
            - -X github.com/circonus-labs/circonus-agent/internal/release.COMMIT={{.ShortCommit}} 
            - -X github.com/circonus-labs/circonus-agent/internal/release.DATE={{.Date}} 
            - -X github.com/circonus-labs/circonus-agent/internal/release.TAG={{.Tag}}

dockers:
    -
        goos: linux
        goarch: amd64
        goarm: ''
        binaries:
            - sbin/circonus-agentd
        image_templates:
            - "circonuslabs/{{.ProjectName}}:{{.Tag}}"
            - "circonuslabs/{{.ProjectName}}:latest"
        skip_push: false
        dockerfile: docker/x86_64/Dockerfile
        build_flag_templates:
            - "--label=org.label-schema.schema-version=1.0"
            - "--label=org.label-schema.version={{.Version}}"
            - "--label=org.label-schema.name={{.ProjectName}}"
    -
        goos: linux
        goarch: arm64
        goarm: ''
        binaries:
            - sbin/circonus-agentd
        image_templates:
            - "circonuslabs/{{.ProjectName}}-arm64:{{.Tag}}"
            - "circonuslabs/{{.ProjectName}}-arm64:latest"
        skip_push: false
        dockerfile: docker/arm64/Dockerfile
        build_flag_templates:
            - "--label=org.label-schema.schema-version=1.0"
            - "--label=org.label-schema.version={{.Version}}"
            - "--label=org.label-schema.name={{.ProjectName}}"

archives:
    - 
      id: default
      name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"

      format: tar.gz

      replacements:
        amd64: x86_64

      format_overrides:
        -
          goos: windows
          format: zip

      files:
        - LICENSE
        - README.md
        - CHANGELOG.md
        - etc/README.md
        - service/*
        - state/README.md
        - plugins/**/*

release:
    github:
        owner: circonus-labs
        name: circonus-agent

    prerelease: auto

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
