project_name: circonus-agent

builds:
    -
        main: main.go

        binary: sbin/circonus-agentd

        env:
            - CGO_ENABLED=0

        flags: -tags dev

        goos:
            - linux
            - darwin
            - windows
            - freebsd
            - solaris

        goarch:
            - amd64
            - arm

        ignore:
            -
                goarch: 386
            - goos: darwin
              goarch: arm
            - goos: freebsd
              goarch: arm

        ldflags: -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.tag={{.Tag}}

archive:
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"

    format: tar.gz

    replacements:
        amd64: 64-bit

    format_overrides:
        -
            goos: windows
            format: zip

    files:
        - LICENSE
        - README.md
        - CHANGELOG.md
        - etc/README.md
        - service/circonus-agent.service
        - state/README.md
        - plugins/*
        - plugins/linux/*
        - plugins/linux/io/*
        - plugins/linux/io/io_latency/*
        - plugins/linux/io/event_harness/*

release:
    github:
        owner: circonus-labs
        name: circonus-agent

    draft: true

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
