project_name: circonus-agent

before:
    hooks:
        - go mod tidy
        - ./build_lint.sh
        - ./build_plugins.sh

builds:
    -
        main: main.go

        binary: sbin/circonus-agentd

        env:
            - CGO_ENABLED=0

        flags: -tags dev

        goos:
            - linux
            - darwin
            - windows
            - freebsd
            - solaris
            - illumos

        goarch:
            - amd64
            - arm

        ignore:
            -
                goarch: 386
            - goos: darwin
              goarch: arm
            - goos: freebsd
              goarch: arm

        ldflags: 
            - -X github.com/circonus-labs/circonus-agent/internal/release.VERSION={{.Version}} 
            - -X github.com/circonus-labs/circonus-agent/internal/release.COMMIT={{.ShortCommit}} 
            - -X github.com/circonus-labs/circonus-agent/internal/release.DATE={{.Date}} 
            - -X github.com/circonus-labs/circonus-agent/internal/release.TAG={{.Tag}}

archives:
    - 
      id: default
      name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"

      format: tar.gz

      replacements:
        amd64: x86_64

      format_overrides:
        -
          goos: windows
          format: zip

      files:
        - LICENSE
        - README.md
        - CHANGELOG.md
        - etc/README.md
        - service/circonus-agent.service
        - state/README.md
        - plugins/**/*

release:
    github:
        owner: circonus-labs
        name: circonus-agent

    prerelease: auto

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
